// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
// app/layout.tsx
// 'use client'
// import { useEffect } from 'react';
// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import 'aos/dist/aos.css';
// import AOS from 'aos';
// import "./globals.css";
// import { useRouter } from 'next/router';

// const inter = Inter({ subsets: ["latin"] });

// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   const router = useRouter  ();
//   useEffect(() => {
//     const handleRouteChange = () => {
//       AOS.refresh();
//     };

//     router.events.on('routeChangeComplete', handleRouteChange);

//     return () => {
//       router.events.off('routeChangeComplete', handleRouteChange);
//     };
//   }, [router.events]);
//   useEffect(() => {
//     AOS.init({
//       offset: 200, // offset (in px) from the original trigger point
//       delay: 0, // values from 0 to 3000, with step 50ms
//       duration: 1000, // values from 0 to 3000, with step 50ms
//       easing: 'ease', // default easing for AOS animations
//       once: true, // whether animation should happen only once - while scrolling down
//       mirror: false, // whether elements should animate out while scrolling past them
//     });
//   }, []);

//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
// app/layout.tsx
import { Inter } from 'next/font/google';
import "./globals.css";
import ClientLayout from '@/components/ClientLayout';
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Et Sec Landing Page",
  description: "Generated by create next app",
};
const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
